services:
  db:
    image: postgres:15-alpine
    container_name: todo-db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./todo-service/src/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  todo-service:
    build:
      context: ./todo-service
      dockerfile: Dockerfile
    container_name: todo-service
    environment:
      DATABASE_URL: postgres://todo_user:todo_pass@db:5432/todo_db
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: ["pnpm", "start"]

  todo-mcp-service:
    build:
      context: ./todo-mcp-service
      dockerfile: Dockerfile
    container_name: todo-mcp-service
    environment:
      # MCP Server Configuration
      MCP_SERVER_PORT: 3001
      LOG_LEVEL: info

      # Todo Service Configuration
      TODO_SERVICE_URL: http://todo-service:3000

      # AI Provider Configuration (default: Ollama)
      USE_CLAUDE_API: false
      OLLAMA_URL: http://host.docker.internal:11434
      OLLAMA_MODEL: tinyllama

      # Claude API Configuration (only used when USE_CLAUDE_API=true)
      # CLAUDE_API_KEY: your_claude_api_key_here
    ports:
      - "3001:3001"
    depends_on:
      todo-service:
        condition: service_started
    volumes:
      # Mount host network for Ollama access
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"

  todo-ui:
    build:
      context: ./todo-ui
      dockerfile: Dockerfile
    container_name: todo-ui
    environment:
      # Next.js Configuration
      NODE_ENV: production
      PORT: 3002

      # MCP Server Configuration
      NEXT_PUBLIC_MCP_SERVER_URL: http://localhost:3001
    ports:
      - "3002:3002"
    depends_on:
      todo-mcp-service:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    develop:
      watch:
        - action: rebuild
          path: ./todo-ui
          ignore:
            - node_modules/
            - .next/
            - .git/

volumes:
  db_data:
